
include ..\Makefile.inc

EFLAGS = -I .. -pz ..

OUTDIR = ..
SOURCES = $(wildcard *.erl)
BEAMS = $(addprefix $(OUTDIR)/,$(SOURCES:.erl=.beam))

ALL : $(BEAMS)

CLEAN :
	-@erase $(BEAMS)

$(OUTDIR)\odbc_connection.beam : odbc_connection.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) odbc_connection.erl

$(OUTDIR)\odbc_pool.beam : odbc_pool.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) odbc_pool.erl

$(OUTDIR)\odbc_queries.beam : odbc_queries.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) -D$(DBTYPE) odbc_queries.erl

